name: hessa_student
version: 1.0.0+1
publish_to: none
description: Hessa Student
environment: 
  sdk: '>=2.18.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  flutter_screenutil: ^5.6.0
  flutter_svg: ^1.1.6
  cached_network_image: ^3.2.3
  dio: ^4.0.6
  shared_preferences: ^2.0.17
  intl: ^0.17.0
  flutter_keyboard_visibility: ^5.4.0
  animated_bottom_navigation_bar: ^1.1.0+1
  time_range: ^1.1.0
  syncfusion_flutter_datepicker: ^20.4.44
  syncfusion_localizations: ^20.4.44
  flutter_localizations:
    sdk: flutter
  image_picker: ^0.8.6+1
  file_picker: ^5.2.5
  infinite_scroll_pagination: ^3.2.0
  lottie: ^2.2.0
  chips_choice: ^3.0.0
  flutter_slidable: ^2.0.0
  flutter_spinkit: ^5.1.0
  pinput: ^2.2.23
  uuid: ^3.0.7
  mime: ^1.0.4
  firebase_auth: ^4.2.5
  firebase_core: ^2.4.1
  flutter_facebook_auth: ^5.0.7
  google_sign_in: ^5.4.4
  firebase_messaging: ^14.2.2
  flutter_local_notifications: ^13.0.0
  path_provider: ^2.0.12
  flutter_widget_from_html: ^0.9.1
  url_launcher: ^6.1.9
  shimmer: ^2.0.0
  flutter_linkify: ^5.0.2
  linkify: ^4.1.0
  better_open_file: ^3.6.4
  equatable: ^2.0.5
  flutter_chat_types: ^3.6.0
  visibility_detector: ^0.3.3
  flutter_link_previewer: ^3.2.0
  flutter_parsed_text: ^2.2.1
  diffutil_dart: ^3.0.0
  photo_view: ^0.14.0
  scroll_to_index: ^3.0.1
  dart_emoji: ^0.2.0+2
  gallery_saver: ^2.3.2
  animator: ^3.2.0
  
dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_native_splash:
  change_app_package_name: ^0.1.3
  flutter_launcher_icons: ^0.12.0
flutter_native_splash:
  color: "#5B83F9"
  android: true
  ios: true
  flutter_test: 
    sdk: flutter
flutter_icons:
  image_path: "assets/images/dars-ios.png"  
  adaptive_icon_foreground: "assets/images/dars_foreground_icon.png"
  adaptive_icon_background: "assets/images/dars_background_icon.png"
  android: true
  ios: true
flutter: 
  uses-material-design: true

  assets: 
    - assets/images/
    - assets/images/splash_backgrounds/
    - assets/flags/
    - assets/lottieJSONS/
    - assets/images/login_or_sign_up/
    - assets/images/flyer_chat/
    - assets/images/flyer_chat/2.0x/
    - assets/images/flyer_chat/3.0x/
    - assets/svg/
    - assets/svg/login/
    - assets/svg/icons/
    - assets/fonts/
    - assets/langs/
  fonts:
    - family: Expo
      fonts:
        - asset: assets/fonts/Expo-Arabic-Bold.ttf
          weight: 800
        - asset: assets/fonts/Expo-Arabic-Book.ttf
          weight: 700
        - asset: assets/fonts/Expo-Arabic-Medium.ttf
          weight: 600
        - asset: assets/fonts/Expo-Arabic-Light.ttf
          weight: 500
