name: hessa_teacher
version: 1.0.0+1
publish_to: none
description: Hessa Teacher App
environment: 
  sdk: '>=2.18.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  flutter_screenutil: ^5.6.0
  flutter_svg: ^1.1.6
  cached_network_image: ^3.2.3
  dio: ^4.0.6
  shared_preferences: ^2.0.17

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

