name: hessa_student
version: 1.0.0+1
publish_to: none
description: Hessa Student App
environment: 
  sdk: '>=2.18.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  flutter_screenutil: ^5.6.0
  flutter_svg: ^1.1.6
  cached_network_image: ^3.2.3
  dio: ^4.0.6
  shared_preferences: ^2.0.17
  intl: ^0.18.0
  translator: ^0.1.7
  intl_phone_field: ^3.1.0
  flutter_keyboard_visibility: ^5.4.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter
  change_app_package_name: ^0.1.3
flutter: 
  uses-material-design: true

  assets: 
    - assets/images/
    - assets/images/login_or_sign_up/
    - assets/images/general_images/
    - assets/svg/
    - assets/svg/login/
    - assets/fonts/
    - assets/langs/
  fonts:
    - family: Expo
      fonts:
        - asset: assets/fonts/Expo-Arabic-Bold.ttf
          weight: 800
        - asset: assets/fonts/Expo-Arabic-Book.ttf
          weight: 700
        - asset: assets/fonts/Expo-Arabic-Medium.ttf
          weight: 600
        - asset: assets/fonts/Expo-Arabic-Light.ttf
          weight: 500
